ClientName: nones
environment: development
traceID: nones0123

# Si bien las sub-variables de "config: " estan seteadas, estas no aplicanl al rabbitmq.
# solo se utilizan para las apps que requieren conexión al mismo.
# estan colocadas en este segmento por una cuestión de orden y reutilización.
# Para mayor flexibilidad, las mismas apps o microservicios son los encargados de 
# crear sus propias queues a demanda. De esta manera no requiero configuraciones hardocreadas en el rabbit ;) 
rabbitmq:
  auth:
    username: admin
    tls:
      enabled: false
  extraPlugins: "rabbitmq_management rabbitmq_management_agent rabbitmq_web_stomp rabbitmq_web_stomp_examples rabbitmq_mqtt rabbitmq_prometheus rabbitmq_top rabbitmq_web_dispatch rabbitmq_web_mqtt rabbitmq_event_exchange rabbitmq_amqp1_0 rabbitmq_peer_discovery_k8s rabbitmq_tracing rabbitmq_stomp rabbitmq_peer_discovery_aws rabbitmq_federation rabbitmq_federation_management"
  configs:
    mqttvhost: /
    queue: infra
    destination_queue: infra
    destination_rk: infra

# customerportal:
#   image: jpradoar/mqtt-customer-portal
#   tag: 1.0.0
#   imagePullPolicy: Always

producer:
  image: jpradoar/mqtt-producer
  tag: latest #2023.06
  imagePullPolicy: Always
  LoadBalancer: 
    enabled: "true" # If true. it will create a LB to internet access

consumer:
  image: jpradoar/mqtt-consumer
  tag: 2023.06
  imagePullPolicy: Always

dbwriter:
  image: jpradoar/mqtt-dbwriter
  tag: 2023.05
  imagePullPolicy: Always

mariadb:
  image: mariadb
  tag: 10.9.4
  imagePullPolicy: Always

webserver:
  image: jpradoar/mqtt-webserver
  tag: 2023.05
  imagePullPolicy: Always

eventexporter:
  image: jpradoar/k8s-event-exporter
  tag: latest
  imagePullPolicy: Always
  aws_arn: arn:aws:iam::123456789012:role/rol-para-acceso-ecr-y-recursos-de-eks