---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}-webserver
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}    
    prometheus.io/scrape: 'true'
    app.mqtt.event.trigger: {{ .Values.traceID }}
spec:
  selector:
    app: {{ .Release.Name }}-webserver
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}    
  ports:
    - name: http
      protocol: TCP     
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}-webserver
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    app.mqtt.event.trigger: {{ .Values.traceID }}   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webserver
      environment: {{ .Values.environment }}
      app.business.client: {{ .Values.ClientName }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webserver
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}
      annotations:
        app.version: {{ .Values.webserver.image }}:{{ .Values.webserver.tag }}
        app.mqtt.event.trigger: {{ .Values.traceID }}      
        environment: {{ .Values.environment }} 
    spec:
      containers:
        - name: webserver
          image: {{ .Values.webserver.image }}:{{ .Values.webserver.tag }}
          imagePullPolicy: {{ .Values.webserver.imagePullPolicy }}
          ports:
            - containerPort: 80          
          env: 
          - name: MARIADB_HOST
            value: "mariadb"
          - name: MARIADB_DATABASE
            value: {{ .Values.mariadb.config.database_name }}
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_password
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_username
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_password  