---
apiVersion: v1
kind: Service
metadata:
  name: dbwriter
  namespace: default
  labels:
    app: {{ .Release.Name }}-dbwriter
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    app: {{ .Release.Name }}-dbwriter
    app.depends: {{ .Release.Name }}-rabbitmq
    app.mqtt.event.trigger: {{ .Values.traceID }}   
spec:
  selector:
    app: dbwriter
  ports:
    - name: metrics
      protocol: TCP     
      port: 9090 
      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbwriter
  namespace: default
  labels:
    app: {{ .Release.Name }}-dbwriter
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    app: {{ .Release.Name }}-dbwriter
    app.depends: {{ .Release.Name }}-rabbitmq
    app.mqtt.event.trigger: {{ .Values.traceID }}   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dbwriter
      environment: {{ .Values.environment }}
      app.business.client: {{ .Values.ClientName }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dbwriter
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}
      annotations:
        app: {{ .Release.Name }}-dbwriter
        app.depends: {{ .Release.Name }}-rabbitmq
        app.mqtt.event.trigger: {{ .Values.traceID }} 
        app.version: {{ .Values.dbwriter.image }}:{{ .Values.dbwriter.tag }}
    spec:
      containers:
        - name: dbwriter
          image: {{ .Values.dbwriter.image }}:{{ .Values.dbwriter.tag }}
          imagePullPolicy: Always   
          env:
          - name: MARIADB_HOST
            value: "mariadb"
          - name: MARIADB_DATABASE
            value: {{ .Values.mariadb.config.database_name }}
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_password
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_username #mariadb_username
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_password #mariadb_password 
          #                 
          - name: mqttport
            value: "5672"
          - name: mqtthost
            value: {{ .Release.Name }}-rabbitmq
          - name: mqttvhost
            value: {{ .Values.rabbitmq.configs.mqttvhost }}
          - name: queue
            value: "clients" #{{ .Values.rabbitmq.configs.queue }}
          - name: destination_queue
            value: {{ .Values.rabbitmq.configs.destination_queue }}
          - name: destination_RK
            value: {{ .Values.rabbitmq.configs.destination_rk }}
          - name: mqttuser
            value: {{ .Values.rabbitmq.auth.username }}
          - name: mqttpass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password  
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5                 