---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-event-exporter-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/rol-para-acceso-ecr-y-recursos-de-eks 


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-event-exporter-cr
  namespace: default
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-event-exporter-cr-binding
subjects:
- kind: ServiceAccount
  name: k8s-event-exporter-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-event-exporter-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-event-exporter
  namespace: default
  labels:
    app: k8s-event-exporter
  annotations:
    imageregistry: "public"
    version: "v1"
    owner: "jpradoar"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-event-exporter
  template:
    metadata:
      labels:
        app: k8s-event-exporter
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: k8s-event-exporter-sa
      containers:
      - name: k8s-event-exporter
        image: jpradoar/k8s-event-exporter:latest
        imagePullPolicy: Always     
#-----------------------------------------          
        resources:
          requests:
            cpu: 50m
            memory: 50Mi          
          limits:
            cpu: 150m
            memory: 150Mi
#-----------------------------------------            
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true  
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
